name = "rate-limiter"
main = "index.ts"
compatibility_date = "2024-03-20"


[[durable_objects.bindings]]
name = "Limiter"
class_name = "RateLimiter"


[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]
